package kotlinx.parcelize;

import android.os.Parcel;
import kotlin.Metadata;
import kotlin.NotImplementedError;
import org.jetbrains.annotations.NotNull;

@Metadata(d1 = {"\u0000,\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0011\n\u0000\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J\u0015\u0010\u0003\u001A\u00028\u00002\u0006\u0010\u0004\u001A\u00020\u0005H&¢\u0006\u0002\u0010\u0006J\u001B\u0010\u0007\u001A\b\u0012\u0004\u0012\u00028\u00000\b2\u0006\u0010\t\u001A\u00020\nH\u0016¢\u0006\u0002\u0010\u000BJ!\u0010\f\u001A\u00020\r*\u00028\u00002\u0006\u0010\u0004\u001A\u00020\u00052\u0006\u0010\u000E\u001A\u00020\nH&¢\u0006\u0002\u0010\u000F¨\u0006\u0010"}, d2 = {"Lkotlinx/parcelize/Parceler;", "T", "", "create", "parcel", "Landroid/os/Parcel;", "(Landroid/os/Parcel;)Ljava/lang/Object;", "newArray", "", "size", "", "(I)[Ljava/lang/Object;", "write", "", "flags", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", "parcelize-runtime"}, k = 1, mv = {1, 9, 0}, xi = 0x30)
public interface Parceler {
    @Metadata(k = 3, mv = {1, 9, 0}, xi = 0x30)
    public static final class DefaultImpls {
        @NotNull
        public static Object[] newArray(@NotNull Parceler parceler0, int v) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    Object create(@NotNull Parcel arg1);

    @NotNull
    Object[] newArray(int arg1);

    void write(Object arg1, @NotNull Parcel arg2, int arg3);
}

