package com.kakao.tistory.presentation.common.tiara;

import kotlin.Metadata;
import kotlin.enums.EnumEntries;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import sd.a;

@Metadata(d1 = {"\u0000\u0011\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0010\u000E\n\u0003\b\u00CC\u0001\b\u0086\u0081\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001J\r\u0010\u0003\u001A\u00020\u0002\u00A2\u0006\u0004\b\u0003\u0010\u0004R\u0017\u0010\b\u001A\u00020\u00028\u0006\u00A2\u0006\f\n\u0004\b\u0005\u0010\u0006\u001A\u0004\b\u0007\u0010\u0004j\u0002\b\tj\u0002\b\nj\u0002\b\u000Bj\u0002\b\fj\u0002\b\rj\u0002\b\u000Ej\u0002\b\u000Fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001Aj\u0002\b\u001Bj\u0002\b\u001Cj\u0002\b\u001Dj\u0002\b\u001Ej\u0002\b\u001Fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b\'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bxj\u0002\byj\u0002\bzj\u0002\b{j\u0002\b|j\u0002\b}j\u0002\b~j\u0002\b\u007Fj\u0003\b\u0080\u0001j\u0003\b\u0081\u0001j\u0003\b\u0082\u0001j\u0003\b\u0083\u0001j\u0003\b\u0084\u0001j\u0003\b\u0085\u0001j\u0003\b\u0086\u0001j\u0003\b\u0087\u0001j\u0003\b\u0088\u0001j\u0003\b\u0089\u0001j\u0003\b\u008A\u0001j\u0003\b\u008B\u0001j\u0003\b\u008C\u0001j\u0003\b\u008D\u0001j\u0003\b\u008E\u0001j\u0003\b\u008F\u0001j\u0003\b\u0090\u0001j\u0003\b\u0091\u0001j\u0003\b\u0092\u0001j\u0003\b\u0093\u0001j\u0003\b\u0094\u0001j\u0003\b\u0095\u0001j\u0003\b\u0096\u0001j\u0003\b\u0097\u0001j\u0003\b\u0098\u0001j\u0003\b\u0099\u0001j\u0003\b\u009A\u0001j\u0003\b\u009B\u0001j\u0003\b\u009C\u0001j\u0003\b\u009D\u0001j\u0003\b\u009E\u0001j\u0003\b\u009F\u0001j\u0003\b\u00A0\u0001j\u0003\b\u00A1\u0001j\u0003\b\u00A2\u0001j\u0003\b\u00A3\u0001j\u0003\b\u00A4\u0001j\u0003\b\u00A5\u0001j\u0003\b\u00A6\u0001j\u0003\b\u00A7\u0001j\u0003\b\u00A8\u0001j\u0003\b\u00A9\u0001j\u0003\b\u00AA\u0001j\u0003\b\u00AB\u0001j\u0003\b\u00AC\u0001j\u0003\b\u00AD\u0001j\u0003\b\u00AE\u0001j\u0003\b\u00AF\u0001j\u0003\b\u00B0\u0001j\u0003\b\u00B1\u0001j\u0003\b\u00B2\u0001j\u0003\b\u00B3\u0001j\u0003\b\u00B4\u0001j\u0003\b\u00B5\u0001j\u0003\b\u00B6\u0001j\u0003\b\u00B7\u0001j\u0003\b\u00B8\u0001j\u0003\b\u00B9\u0001j\u0003\b\u00BA\u0001j\u0003\b\u00BB\u0001j\u0003\b\u00BC\u0001j\u0003\b\u00BD\u0001j\u0003\b\u00BE\u0001j\u0003\b\u00BF\u0001j\u0003\b\u00C0\u0001j\u0003\b\u00C1\u0001j\u0003\b\u00C2\u0001j\u0003\b\u00C3\u0001j\u0003\b\u00C4\u0001j\u0003\b\u00C5\u0001j\u0003\b\u00C6\u0001j\u0003\b\u00C7\u0001j\u0003\b\u00C8\u0001j\u0003\b\u00C9\u0001j\u0003\b\u00CA\u0001j\u0003\b\u00CB\u0001j\u0003\b\u00CC\u0001j\u0003\b\u00CD\u0001\u00A8\u0006\u00CE\u0001"}, d2 = {"Lcom/kakao/tistory/presentation/common/tiara/TistoryTiaraActionType;", "", "", "getActionTypeValue", "()Ljava/lang/String;", "a", "Ljava/lang/String;", "getType", "type", "NONE", "CLICK_CLOSE", "CLICK_COMPLETE", "CLICK_NEXT", "CLICK_CHANGE", "CLICK_OK", "CLICK_CANCEL", "CLICK_CLOSE_BUTTON", "CLICK_LATER", "CLICK_NOTICE", "CLICK_IMAGE_SETTING", "CLICK_IMAGE_DELETE", "CLICK_GALLERY", "CLICK_LOGIN_KAKAO", "CLICK_LOGIN_KAKAO_DIRECTLY", "CLICK_LOGIN_TISTORY", "CLICK_ACCOUNT_FIND", "CLICK_ACCOUNT_SETTING", "CLICK_APP_BAR_TISTORY_LOGO", "CLICK_APP_BAR_SEARCH", "CLICK_APP_BAR_PROFILE_IMAGE", "CLICK_APP_BAR_TITLE", "CLICK_PROFILE_IMAGE", "CLICK_NICKNAME", "CLICK_BLOG_SWITCH", "CLICK_GLOBAL_SETTING", "CLICK_BOTTOM_NAVIGATION_HOME", "CLICK_BOTTOM_NAVIGATION_FEED", "CLICK_BOTTOM_NAVIGATION_EDITOR", "CLICK_BOTTOM_NAVIGATION_NOTIFICATION", "CLICK_BOTTOM_NAVIGATION_BLOG_TOP", "CLICK_HOME_SLOT_TODAY", "CLICK_HOME_SLOT_BEST", "CLICK_HOME_SLOT_BANNER", "CLICK_HOME_SLOT_CATEGORY_GROUP", "CLICK_HOME_SLOT_CATEGORY_ENTRY", "CLICK_HOME_SLOT_CATEGORY_MORE", "CLICK_HOME_SLOT_CREATOR_FOLLOW", "CLICK_HOME_SLOT_CREATOR_ENTRY", "CLICK_HOME_SLOT_CREATOR_BLOG", "CLICK_HOME_SLOT_CREATOR_MORE", "CLICK_HOME_SLOT_SUBSCRIPTION_BLOG", "CLICK_HOME_SLOT_SUBSCRIPTION_ENTRY", "CLICK_HOME_SLOT_SUBSCRIPTION_MORE", "CLICK_HOME_SLOT_SUBSCRIPTION_FOLLOW", "CLICK_HOME_SLOT_SUPPORT", "CLICK_HOME_SLOT_SUPPORT_MORE", "CLICK_HOME_SLOT_FOCUS", "CLICK_HOME_SLOT_TIP", "CLICK_TOP_MESSAGE", "CLICK_REFERER_KEYWORD", "CLICK_REFERER_ETC", "CLICK_REFERER_ETC_URL", "CLICK_RECENT_POST", "CLICK_TOP_ENTRY", "CLICK_TOP_ENTRY_ALL", "CLICK_FOLLOWING", "CLICK_FOLLOWER", "CLICK_FOLLOWER_ALL", "CLICK_ENTRY_ITEM", "LONG_CLICK_ENTRY_ITEM", "CLICK_BLOG", "CLICK_BLOG_OF_ENTRY", "CLICK_FOLLOW", "CLICK_FOLLOW_CANCEL", "CLICK_SORT", "CLICK_PERIOD_SORT", "CLICK_SORT_ITEM", "CLICK_PERIOD_SORT_ITEM", "CLICK_METRIC_SORT_ITEM", "CLICK_NOTIFICATION_ITEM", "CLICK_NOTIFICATION_BANNER", "CLICK_NOTIFICATION_ITEM_DELETE", "CLICK_SEE_ENTRY_VIEW", "CLICK_BLOG_TOP_BLOCK", "CLICK_BLOG_TOP_UNBLOCK", "CLICK_BLOG_TOP_REPORT", "CLICK_BLOG_TOP_CATEGORY", "CLICK_BLOG_TOP_SHARE_URL", "CLICK_BLOG_TOP_DESCRIPTION_READ_MORE", "CLICK_BLOG_TOP_FOLLOWER_COUNT", "CLICK_BLOG_TOP_FOLLOWING_COUNT", "CLICK_BLOG_TOP_SETTING", "CLICK_BLOG_TOP_GUEST_BOOK", "CLICK_BLOG_STATISTICS_STAT", "CLICK_BLOG_STATISTICS_LOG", "CLICK_BLOG_STATISTICS_KEYWORD", "CLICK_BLOG_STATISTICS_REVENUE", "CLICK_BLOG_STATISTICS_SWIPE", "CLICK_BLOG_TOP_CHALLENGE_BANNER", "CLICK_BLOG_TOP_CHALLENGE_AUTH", "CLICK_NOTICE_ITEM", "CLICK_NOTICE_SEE_ALL", "CLICK_CATEGORY", "CLICK_CATEGORY_ITEM", "CLICK_HOME_SUBJECT_SELECTOR", "CLICK_HOME_SUBJECT", "CLICK_RECENT_TAG", "CLICK_VISIBILITY_SETTING", "CLICK_VISIBILITY_MENU", "CLICK_VISIBILITY_PUBLIC", "CLICK_VISIBILITY_PROTECTED", "CLICK_VISIBILITY_PRIVATE", "CLICK_VISIBILITY_PROTECTED_PASSWORD", "CLICK_PUBLISH_DATE", "CLICK_PUBLISH", "CLICK_MODIFY", "CLICK_STATISTICS", "CLICK_DELETE", "CLICK_PIN", "CLICK_UNPIN", "CLICK_LIKE", "CLICK_COMMENT", "CLICK_SHARE", "CLICK_MORE", "CLICK_REPORT", "CLICK_REPORT_COMPLETE", "CLICK_COMMENT_REPLY", "CLICK_COMMENT_READ_MORE", "CLICK_COMMENT_COMPLETE", "CLICK_COMMENT_MODIFY", "CLICK_REPLY_SEE_ALL", "CLICK_COMMENT_MODIFY_UPLOAD", "CLICK_GUESTBOOK_MODIFY_UPLOAD", "CLICK_SETTING_ACCOUNT", "CLICK_SETTING_DEFAULT_BLOG", "CLICK_SETTING_NOTIFICATION", "CLICK_SETTING_NOTICE", "CLICK_SETTING_APP_INFO", "CLICK_SETTING_TERMS_AND_CONDITIONS", "CLICK_SETTING_PRIVACY_POLICY", "CLICK_SETTING_OPEN_SOURCE_LICENSE", "CLICK_SETTING_HELP", "CLICK_SETTING_QUESTION", "CLICK_SETTING_LEAVE", "CLICK_SETTING_LEAVE_AGREEMENT", "CLICK_SETTING_LEAVE_BUTTON", "CLICK_NICKNAME_CHANGE", "CLICK_PASSWORD_CHANGE", "CLICK_PASSWORD_FIND", "CLICK_SETTING_NOTIFICATION_ALL", "CLICK_SETTING_NOTIFICATION_COMMENT", "CLICK_SETTING_NOTIFICATION_BLOG_INVITATION", "CLICK_SETTING_NOTIFICATION_FOLLOW", "CLICK_SETTING_NOTIFICATION_NEW_ENTRY", "CLICK_SETTING_NOTIFICATION_CHALLENGE", "CLICK_SETTING_NOTIFICATION_ETIQUETTE", "CLICK_SEARCH_INPUT_FIELD", "CLICK_SEARCH_INPUT_CLEAR", "CLICK_SEARCH_SEARCHING", "CLICK_SEARCH_ALL_SEARCHING", "CLICK_SEARCH_SEARCHING_FROM_KEYBOARD", "CLICK_SEARCH_RECENT_KEYWORD", "CLICK_SEARCH_RECENT_KEYWORD_REMOVE", "CLICK_SEARCH_RECENT_KEYWORD_REMOVE_ALL", "CLICK_SEARCH_RECENT_KEYWORD_ON", "CLICK_SEARCH_RECENT_KEYWORD_OFF", "CLICK_SEARCH_SUGGEST_KEYWORD", "CLICK_SEARCH_SUGGEST_KEYWORD_ARROW", "CLICK_SEARCH_SUGGEST_KEYWORD_ON", "CLICK_SEARCH_SUGGEST_KEYWORD_OFF", "CLICK_SEARCH_RESULT_TAB", "CLICK_APP_UPDATE", "CLICK_SEE_DETAIL", "CLICK_SETTING_TRANSFER", "CLICK_TRANSFER", "CLICK_TRANSFER_NO_MORE_SEE_WEEKEND", "CLICK_REVENUE_VENDOR_SELECT_MENU", "CLICK_REVENUE_VENDOR_SELECT_ITEM", "CLICK_REVENUE_PERIOD", "CLICK_REVENUE_GRAPH", "CLICK_REVENUE_CREATOR", "CLICK_STATISTICS_METRIC", "CLICK_STATISTICS_GRAPH_ITEM", "CLICK_CHALLENGE_AUTH", "CLICK_CHALLENGE_SUCCESS", "CLICK_CHALLENGE_SERVICE_CATEGORY", "CLICK_CHALLENGE_SERVICE_CATEGORY_CONTINUE", "CLICK_CHALLENGE_ADD_TAG", "PAGE_TRANSFER_START", "PAGE_TRANSFER_FINAL_CONFIRM", "PAGE_COMMENT_MODIFICATION", "PAGE_CHALLENGE_AUTH_DIALOG", "PAGE_CHALLENGE_SUCCESS_DIALOG", "PAGE_CHALLENGE_SERVICE_CATEGORY", "LONG_CLICK_BOTTOM_NAVIGATION_BLOG_TOP", "SWIPE_HOME_STATISTICS", "SWIPE_CONTENT", "SWIPE_SEARCH_RESULT_TAB", "SIGN_UP_ALL_AGREE", "SIGN_UP_REQUIREMENT_AGREE", "SIGN_UP_TALK_AGREE", "SIGN_UP_AGREE_DONE", "BLOG_INFO_NAME", "BLOG_INFO_ADDRESS", "BLOG_INFO_NICKNAME", "BLOG_INFO_COMPLETE", "presentation_prodRelease"}, k = 1, mv = {1, 9, 0}, xi = 0x30)
public enum TistoryTiaraActionType {
    NONE("미지정", TiaraActionCategory.NONE),
    CLICK_CLOSE("닫기"),
    CLICK_COMPLETE("완료"),
    CLICK_NEXT("다음"),
    CLICK_CHANGE("변경"),
    CLICK_OK("확인"),
    CLICK_CANCEL("취소"),
    CLICK_CLOSE_BUTTON("닫기 버튼"),
    CLICK_LATER("다음에 하기"),
    CLICK_NOTICE("공지사항"),
    CLICK_IMAGE_SETTING("이미지 설정"),
    CLICK_IMAGE_DELETE("이미지 삭제"),
    CLICK_GALLERY("앨범에서 선택"),
    CLICK_LOGIN_KAKAO("카카오계정 로그인"),
    CLICK_LOGIN_KAKAO_DIRECTLY("카카오계정 직접 입력"),
    CLICK_LOGIN_TISTORY("올드계정 로그인"),
    CLICK_ACCOUNT_FIND("계정 정보 찾기"),
    CLICK_ACCOUNT_SETTING("계정 설정"),
    CLICK_APP_BAR_TISTORY_LOGO("T아이콘"),
    CLICK_APP_BAR_SEARCH("검색 진입"),
    CLICK_APP_BAR_PROFILE_IMAGE("프로필이미지"),
    CLICK_APP_BAR_TITLE("gnb타이틀"),
    CLICK_PROFILE_IMAGE("프로필 이미지"),
    CLICK_NICKNAME("닉네임"),
    CLICK_BLOG_SWITCH("블로그 전환"),
    CLICK_GLOBAL_SETTING("전체 설정"),
    CLICK_BOTTOM_NAVIGATION_HOME("홈 탭"),
    CLICK_BOTTOM_NAVIGATION_FEED("피드 탭"),
    CLICK_BOTTOM_NAVIGATION_EDITOR("에디터 탭"),
    CLICK_BOTTOM_NAVIGATION_NOTIFICATION("알림 탭"),
    CLICK_BOTTOM_NAVIGATION_BLOG_TOP("내 블로그 탭"),
    CLICK_HOME_SLOT_TODAY("오늘의 티스토리"),
    CLICK_HOME_SLOT_BEST("TOP5"),
    CLICK_HOME_SLOT_BANNER("메인배너"),
    CLICK_HOME_SLOT_CATEGORY_GROUP("대카테고리 버튼"),
    CLICK_HOME_SLOT_CATEGORY_ENTRY("카테고리 인기글"),
    CLICK_HOME_SLOT_CATEGORY_MORE("인기글 더보기"),
    CLICK_HOME_SLOT_CREATOR_FOLLOW("크리에이터 구독하기"),
    CLICK_HOME_SLOT_CREATOR_ENTRY("크리에이터 추천글"),
    CLICK_HOME_SLOT_CREATOR_BLOG("크리에이터 블로그"),
    CLICK_HOME_SLOT_CREATOR_MORE("크리에이터 더보기"),
    CLICK_HOME_SLOT_SUBSCRIPTION_BLOG("구독 급상승 블로그"),
    CLICK_HOME_SLOT_SUBSCRIPTION_ENTRY("구독 급상승 추천글"),
    CLICK_HOME_SLOT_SUBSCRIPTION_MORE("구독 급상승 더보기"),
    CLICK_HOME_SLOT_SUBSCRIPTION_FOLLOW("구독 급상승 구독하기"),
    CLICK_HOME_SLOT_SUPPORT("응원글"),
    CLICK_HOME_SLOT_SUPPORT_MORE("응원글 더보기"),
    CLICK_HOME_SLOT_FOCUS("섹션별 인기글"),
    CLICK_HOME_SLOT_TIP("팁"),
    CLICK_TOP_MESSAGE("탑메세지 링크"),
    CLICK_REFERER_KEYWORD("유입 키워드"),
    CLICK_REFERER_ETC("기타 유입 자세히 보기"),
    CLICK_REFERER_ETC_URL("기타 유입 URL"),
    CLICK_RECENT_POST("최근글"),
    CLICK_TOP_ENTRY("인기글"),
    CLICK_TOP_ENTRY_ALL("인기글 모두보기"),
    CLICK_FOLLOWING("구독중"),
    CLICK_FOLLOWER("구독자"),
    CLICK_FOLLOWER_ALL("구독자 모두보기"),
    CLICK_ENTRY_ITEM("글"),
    LONG_CLICK_ENTRY_ITEM("콘텐츠", TiaraActionCategory.LONG_CLICK),
    CLICK_BLOG("블로그"),
    CLICK_BLOG_OF_ENTRY("글의 블로그"),
    CLICK_FOLLOW("구독"),
    CLICK_FOLLOW_CANCEL("구독취소"),
    CLICK_SORT("선택자"),
    CLICK_PERIOD_SORT("기간선택자"),
    CLICK_SORT_ITEM("선택자 항목"),
    CLICK_PERIOD_SORT_ITEM("기간항목"),
    CLICK_METRIC_SORT_ITEM("지표타입"),
    CLICK_NOTIFICATION_ITEM("알림 1건"),
    CLICK_NOTIFICATION_BANNER("알림 내 배너"),
    CLICK_NOTIFICATION_ITEM_DELETE("알림 삭제"),
    CLICK_SEE_ENTRY_VIEW("본문보기"),
    CLICK_BLOG_TOP_BLOCK("블로그 차단"),
    CLICK_BLOG_TOP_UNBLOCK("블로그 차단해제하기"),
    CLICK_BLOG_TOP_REPORT("블로그 신고하기"),
    CLICK_BLOG_TOP_CATEGORY("블로그 탑 > 스토리 크리에이터 표기"),
    CLICK_BLOG_TOP_SHARE_URL("블로그URL 공유"),
    CLICK_BLOG_TOP_DESCRIPTION_READ_MORE("설명 더보기"),
    CLICK_BLOG_TOP_FOLLOWER_COUNT("구독자 수"),
    CLICK_BLOG_TOP_FOLLOWING_COUNT("구독중 수"),
    CLICK_BLOG_TOP_SETTING("블로그 설정"),
    CLICK_BLOG_TOP_GUEST_BOOK("방명록"),
    CLICK_BLOG_STATISTICS_STAT("블로그 통계"),
    CLICK_BLOG_STATISTICS_LOG("유입 로그"),
    CLICK_BLOG_STATISTICS_KEYWORD("유입 키워드"),
    CLICK_BLOG_STATISTICS_REVENUE("수익"),
    CLICK_BLOG_STATISTICS_SWIPE("홈 통계카드", TiaraActionCategory.SWIPE),
    CLICK_BLOG_TOP_CHALLENGE_BANNER("챌린지 자세히 보기"),
    CLICK_BLOG_TOP_CHALLENGE_AUTH("카카오계정 본인인증"),
    CLICK_NOTICE_ITEM("공지 글"),
    CLICK_NOTICE_SEE_ALL("공지 모두보기"),
    CLICK_CATEGORY("카테고리 선택자"),
    CLICK_CATEGORY_ITEM("카테고리 항목"),
    CLICK_HOME_SUBJECT_SELECTOR("홈주제 선택자"),
    CLICK_HOME_SUBJECT("홈주제"),
    CLICK_RECENT_TAG("최신 태그"),
    CLICK_VISIBILITY_SETTING("공개설정"),
    CLICK_VISIBILITY_MENU("공개설정변경"),
    CLICK_VISIBILITY_PUBLIC("공개"),
    CLICK_VISIBILITY_PROTECTED("보호"),
    CLICK_VISIBILITY_PRIVATE("비공개"),
    CLICK_VISIBILITY_PROTECTED_PASSWORD("비밀번호"),
    CLICK_PUBLISH_DATE("발행일"),
    CLICK_PUBLISH("발행 버튼"),
    CLICK_MODIFY("수정"),
    CLICK_STATISTICS("통계"),
    CLICK_DELETE("삭제"),
    CLICK_PIN("고정"),
    CLICK_UNPIN("고정해제"),
    CLICK_LIKE("공감"),
    CLICK_COMMENT("댓글"),
    CLICK_SHARE("공유"),
    CLICK_MORE("더보기"),
    CLICK_REPORT("신고"),
    CLICK_REPORT_COMPLETE("신고 접수"),
    CLICK_COMMENT_REPLY("답글 버튼"),
    CLICK_COMMENT_READ_MORE("댓글 더보기"),
    CLICK_COMMENT_COMPLETE("댓글 등록"),
    CLICK_COMMENT_MODIFY("댓글 수정"),
    CLICK_REPLY_SEE_ALL("이전 답글 모두보기"),
    CLICK_COMMENT_MODIFY_UPLOAD("댓글수정 등록"),
    CLICK_GUESTBOOK_MODIFY_UPLOAD("방명록수정 등록"),
    CLICK_SETTING_ACCOUNT("계정설정"),
    CLICK_SETTING_DEFAULT_BLOG("대표블로그설정"),
    CLICK_SETTING_NOTIFICATION("알림설정"),
    CLICK_SETTING_NOTICE("서비스공지"),
    CLICK_SETTING_APP_INFO("앱정보"),
    CLICK_SETTING_TERMS_AND_CONDITIONS("이용약관"),
    CLICK_SETTING_PRIVACY_POLICY("개인정보처리방침"),
    CLICK_SETTING_OPEN_SOURCE_LICENSE("오픈소스라이선스"),
    CLICK_SETTING_HELP("도움말"),
    CLICK_SETTING_QUESTION("문의하기"),
    CLICK_SETTING_LEAVE("탈퇴하기"),
    CLICK_SETTING_LEAVE_AGREEMENT("탈퇴동의"),
    CLICK_SETTING_LEAVE_BUTTON("탈퇴하기버튼"),
    CLICK_NICKNAME_CHANGE("닉네임 변경"),
    CLICK_PASSWORD_CHANGE("비밀번호 변경"),
    CLICK_PASSWORD_FIND("비밀번호 찾기"),
    CLICK_SETTING_NOTIFICATION_ALL("푸시 알림"),
    CLICK_SETTING_NOTIFICATION_COMMENT("댓글답글 알림"),
    CLICK_SETTING_NOTIFICATION_BLOG_INVITATION("팀블로그 알림"),
    CLICK_SETTING_NOTIFICATION_FOLLOW("구독 알림"),
    CLICK_SETTING_NOTIFICATION_NEW_ENTRY("새 글 알림"),
    CLICK_SETTING_NOTIFICATION_CHALLENGE("챌린지 알림"),
    CLICK_SETTING_NOTIFICATION_ETIQUETTE("방해금지"),
    CLICK_SEARCH_INPUT_FIELD("입력 필드"),
    CLICK_SEARCH_INPUT_CLEAR("필드 비우기"),
    CLICK_SEARCH_SEARCHING("검색하기"),
    CLICK_SEARCH_ALL_SEARCHING("전체검색하기"),
    CLICK_SEARCH_SEARCHING_FROM_KEYBOARD("검색_키보드"),
    CLICK_SEARCH_RECENT_KEYWORD("최근 검색어 1건"),
    CLICK_SEARCH_RECENT_KEYWORD_REMOVE("최근 검색어 1건 삭제"),
    CLICK_SEARCH_RECENT_KEYWORD_REMOVE_ALL("최근 검색어 전체삭제"),
    CLICK_SEARCH_RECENT_KEYWORD_ON("최근 검색어 저장 켜기"),
    CLICK_SEARCH_RECENT_KEYWORD_OFF("최근 검색어 저장 끄기"),
    CLICK_SEARCH_SUGGEST_KEYWORD("자동완성 1건"),
    CLICK_SEARCH_SUGGEST_KEYWORD_ARROW("자동완성 화살표"),
    CLICK_SEARCH_SUGGEST_KEYWORD_ON("자동완성 켜기"),
    CLICK_SEARCH_SUGGEST_KEYWORD_OFF("자동완성 끄기"),
    CLICK_SEARCH_RESULT_TAB("검색 결과 탭"),
    CLICK_APP_UPDATE("업데이트"),
    CLICK_SEE_DETAIL("자세히보기"),
    CLICK_SETTING_TRANSFER("카카오계정 전환"),
    CLICK_TRANSFER("전환하기"),
    CLICK_TRANSFER_NO_MORE_SEE_WEEKEND("일주일안보기"),
    CLICK_REVENUE_VENDOR_SELECT_MENU("매체선택자"),
    CLICK_REVENUE_VENDOR_SELECT_ITEM("매체선택 항목"),
    CLICK_REVENUE_PERIOD("기간항목"),
    CLICK_REVENUE_GRAPH("수익 그래프"),
    CLICK_REVENUE_CREATOR("정산센터 바로가기"),
    CLICK_STATISTICS_METRIC("지표타입선택자"),
    CLICK_STATISTICS_GRAPH_ITEM("그래프"),
    CLICK_CHALLENGE_AUTH("본인인증 하기"),
    CLICK_CHALLENGE_SUCCESS("참여현황 보기"),
    CLICK_CHALLENGE_SERVICE_CATEGORY("홈주제 선택하기"),
    CLICK_CHALLENGE_SERVICE_CATEGORY_CONTINUE("그대로 발행하기"),
    CLICK_CHALLENGE_ADD_TAG("챌린지 태그 추가 버튼"),
    PAGE_TRANSFER_START("전환시작안내", TiaraActionCategory.PAGE),
    PAGE_TRANSFER_FINAL_CONFIRM("전환최종확인", TiaraActionCategory.PAGE),
    PAGE_COMMENT_MODIFICATION("댓글수정", TiaraActionCategory.PAGE),
    PAGE_CHALLENGE_AUTH_DIALOG("카카오계정 본인인증 안내", TiaraActionCategory.PAGE),
    PAGE_CHALLENGE_SUCCESS_DIALOG("참여 성공 안내", TiaraActionCategory.PAGE),
    PAGE_CHALLENGE_SERVICE_CATEGORY("홈주제 선택 안내", TiaraActionCategory.PAGE),
    LONG_CLICK_BOTTOM_NAVIGATION_BLOG_TOP("내 블로그 탭", TiaraActionCategory.LONG_CLICK),
    SWIPE_HOME_STATISTICS("홈 통계카드", TiaraActionCategory.SWIPE),
    SWIPE_CONTENT("콘텐츠", TiaraActionCategory.SWIPE),
    SWIPE_SEARCH_RESULT_TAB("검색 결과 탭", TiaraActionCategory.SWIPE),
    SIGN_UP_ALL_AGREE("티스토리 시작하기 > 모두 동의", TiaraActionCategory.NONE),
    SIGN_UP_REQUIREMENT_AGREE("티스토리 시작하기 > 필수 항목 동의", TiaraActionCategory.NONE),
    SIGN_UP_TALK_AGREE("티스토리 시작하기 > 스토리 톡채널 항목 동의", TiaraActionCategory.NONE),
    SIGN_UP_AGREE_DONE("티스토리 시작하기 > 시작하기 버튼", TiaraActionCategory.NONE),
    BLOG_INFO_NAME("블로그정보입력_블로그 이름", TiaraActionCategory.NONE),
    BLOG_INFO_ADDRESS("블로그정보입력_블로그 주소", TiaraActionCategory.NONE),
    BLOG_INFO_NICKNAME("블로그정보입력_블로그 닉네임", TiaraActionCategory.NONE),
    BLOG_INFO_COMPLETE("블로그정보입력_완료", TiaraActionCategory.NONE);

    public final String a;
    public final TiaraActionCategory b;
    public static final TistoryTiaraActionType[] c;
    public static final EnumEntries d;

    static {
        TistoryTiaraActionType.c = arr_tistoryTiaraActionType;
        Intrinsics.checkNotNullParameter(arr_tistoryTiaraActionType, "entries");
        TistoryTiaraActionType.d = new a(arr_tistoryTiaraActionType);
    }

    public TistoryTiaraActionType(String s1) {
        this.a = s1;
        this.b = TiaraActionCategory.CLICK;
    }

    public TistoryTiaraActionType(String s1, TiaraActionCategory tiaraActionCategory0) {
        this.a = s1;
        this.b = tiaraActionCategory0;
    }

    public static final TistoryTiaraActionType[] a() [...] // Inlined contents

    @NotNull
    public final String getActionTypeValue() {
        return androidx.room.a.z(this.a, this.b.getValue());
    }

    @NotNull
    public static EnumEntries getEntries() {
        return TistoryTiaraActionType.d;
    }

    @NotNull
    public final String getType() {
        return this.a;
    }
}

